class Autogenerated {
  String? _msg;
  Body? _body;

  Autogenerated({String? msg, Body? body}) {
    if (msg != null) {
      this._msg = msg;
    }
    if (body != null) {
      this._body = body;
    }
  }

  String? get msg => _msg;
  set msg(String? msg) => _msg = msg;
  Body? get body => _body;
  set body(Body? body) => _body = body;

  Autogenerated.fromJson(Map<String, dynamic> json) {
    _msg = json['msg'];
    _body = json['body'] != null ? new Body.fromJson(json['body']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['msg'] = this._msg;
    if (this._body != null) {
      data['body'] = this._body!.toJson();
    }
    return data;
  }
}

class Body {
  String? _token;

  Body({String? token}) {
    if (token != null) {
      this._token = token;
    }
  }

  String? get token => _token;
  set token(String? token) => _token = token;

  Body.fromJson(Map<String, dynamic> json) {
    _token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['token'] = this._token;
    return data;
  }
}
