class Autogenerated {
  String? msg;
  Body? body;

  Autogenerated({this.msg, this.body});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    msg = json['msg'];
    body = json['body'] != null ? new Body.fromJson(json['body']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['msg'] = this.msg;
    if (this.body != null) {
      data['body'] = this.body!.toJson();
    }
    return data;
  }
}

class Body {
  String? token;
  User? user;

  Body({this.token, this.user});

  Body.fromJson(Map<String, dynamic> json) {
    token = json['token'];
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['token'] = this.token;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  int? iD;
  String? name;
  String? password;
  String? email;
  String? role;
  ImageLoc? imageLoc;

  User(
      {this.iD,
      this.name,
      this.password,
      this.email,
      this.role,
      this.imageLoc});

  User.fromJson(Map<String, dynamic> json) {
    iD = json['ID'];
    name = json['Name'];
    password = json['Password'];
    email = json['Email'];
    role = json['Role'];
    imageLoc = json['ImageLoc'] != null
        ? new ImageLoc.fromJson(json['ImageLoc'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['ID'] = this.iD;
    data['Name'] = this.name;
    data['Password'] = this.password;
    data['Email'] = this.email;
    data['Role'] = this.role;
    if (this.imageLoc != null) {
      data['ImageLoc'] = this.imageLoc!.toJson();
    }
    return data;
  }
}

class ImageLoc {
  String? string;
  bool? valid;

  ImageLoc({this.string, this.valid});

  ImageLoc.fromJson(Map<String, dynamic> json) {
    string = json['String'];
    valid = json['Valid'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['String'] = this.string;
    data['Valid'] = this.valid;
    return data;
  }
}
